GCC = /usr/local/Cellar/gcc/4.9.1/bin/gcc-4.9
G++ = /usr/local/Cellar/gcc/4.9.1/bin/g++-4.9

timerExample:
	$(GCC) timerExample.c -o timerExample -Wall -lrt

read:
	$(GCC) forkReadFile.c -o read -Wall -DFORK_READ
